apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ym1wfa906-go 
  janus-idp.io/tekton: ym1wfa906-go
  backstage.io/kubernetes-id: ym1wfa906-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ym1wfa906-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  