apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ym1wfa906-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ym1wfa906-go 
  name: ym1wfa906-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ym1wfa906-go 
